# -*- coding: utf-8 -*-
"""1st project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kC4RiRRizIQVeM_fJxmNnD8hgZZyFqWX
"""

operadores = {1: 'Soma', 2: 'Subtração', 3: 'Multiplicação', 4: 'Divisão', 5: 'Sair'} #Opções de operações
operador = 6 #Valor de controle para a entrada de valor no while

while operador == 6:
  print('Escolha o que gostaria de ser feito:')
  for k,v in operadores.items(): #comando para percorrer e imprimir os operadores
    print(k, '-', v)

  operador = int(input(': ')) #recebe a informação de qual operação será feita e converte em numero inteiro
  if operador == 5: #Condição para sair do loop
    break
  elif operador not in operadores.keys(): #Condição para caso o usuáo escolha uma opção que não está nas opções listadas
    print('Opção errada...')
  else:
    primeiro_numero = (int(input('Insira o primeiro número: ')))
    segundo_numero =  (int(input('Insira o segundo número: ')))
#Condições para efetuar o calculo na opção desejada pelo usuário
  if operador == 1:
    print('O resultado é:', primeiro_numero + segundo_numero)
  elif operador == 2:
    print('O resultado é:', primeiro_numero - segundo_numero)
  elif operador == 3:
    print('O resultado é:', primeiro_numero * segundo_numero)
  elif operador == 4:
    if segundo_numero == 0: #Condição para caso o segundo numero informado seja zero
      print('Nenhum número pode ser dividido por zero')
    else:
      print('O resultado é:', primeiro_numero / segundo_numero)
  print('') #Somente para dar um espaço entre os loops
  operador = 6 #para a variavel continuar na condição do loop

